"""
Project Euler Problem 2: https://projecteuler.net/problem=2
Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
References:
    - https://en.wikipedia.org/wiki/Fibonacci_number
"""


def fibonacci() -> int:
    """
    Returns the sum of all even-valued terms in the Fibonacci sequence that are less than 4000000.

     >>> fibonacci()
    4613732
    """

    nterms = 32

    n1, n2 = 1, 2
    count = 0

    total = []

    while count < nterms:
        total.append(n1)
        nth = n1 + n2
        # update values
        n1 = n2
        n2 = nth
        count += 1

    even_sum = 0

    for n in total:
        if n % 2 == 0:
            even_sum += n

    return even_sum


if __name__ == "__main__":
    print(fibonacci())
