# These are supported funding model platforms

github: [cclauss]
patreon: cclauss
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: TheAlgorithms
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['http://paypal.me/TheAlgorithms/1000', 'https://donorbox.org/thealgorithms']
