"""
What Is the Nominal Rate of Return?

The nominal rate of return is the amount of money generated by an investment before factoring in expenses such as taxes,
investment fees, and inflation. If an investment generated a 10% return, the nominal rate would equal 10%.
After factoring in inflation during the investment period, the actual ("real") return would likely be lower.

Source: https://www.investopedia.com/terms/n/nominal-rate-of-return.asp



What Is the Inflation-Adjusted Return?

The inflation-adjusted return is the measure of return that takes into account the time period's inflation rate.
The purpose of the inflation-adjusted return metric is to reveal the return on an investment after removing
the effects of inflation.

Removing the effects of inflation from the return of an investment allows the investor to see the true earning potential
of the security without external economic forces.

Source: https://www.investopedia.com/terms/i/inflation_adjusted_return.asp

"""


def nominal_rate_of_return(current_market_value: int, original_investment_value: int):
    """
    >>> nominal_rate_of_return(108000,100000)
    8.0

    >>> nominal_rate_of_return(800,1000)
    -20.0"""
    nominal_rate_of_return = (
        (current_market_value - original_investment_value) / original_investment_value
    ) * 100
    return nominal_rate_of_return


def inflation_adjusted_rate_of_return(
    ending_price: int,
    beginning_price: int,
    dividends: int,
    ending_cpi_level: int,
    beginning_cpi_level: int,
):
    """
    >>> inflation_adjusted_rate_of_return(90000,75000,2500,721,700)
    19.74

    >>> inflation_adjusted_rate_of_return(75000,90000,0,721,700)
    -19.09

    >>> inflation_adjusted_rate_of_return(75000,90000,-10,721,700)
    Traceback (most recent call last):
    ...
    Exception: Dividend cannot be negative.
    """
    if dividends < 0:
        raise Exception("Dividend cannot be negative.")

    # Step 1: Calculate Stock Return
    stock_return = (ending_price - beginning_price + dividends) / beginning_price

    # Step 2: Calculate Inflation
    inflation = (ending_cpi_level - beginning_cpi_level) / beginning_cpi_level

    # Step 3: Calculate Inflation adjusted return
    inflation_adjusted_rate_of_return = ((1 + stock_return) / (1 + inflation) - 1) * 100
    return round(inflation_adjusted_rate_of_return, 2)


if __name__ == "__main__":
    import doctest

    doctest.testmod()
