print("Harry is awesome".capitalize())
print("HARRY IS KING".lower())
print("harry is hot".upper())
print("Harry potter and the half-blood prince".title())
print("AVENGER:the war of infinity".swapcase())