name: Test DevContainer Build

on:
  push:
    paths:
      - ".devcontainer/**"
      - ".github/workflows/devcontainer_ci.yml"
  pull_request:
    paths:
      - ".devcontainer/**"
      - ".github/workflows/devcontainer_ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: "true"
