# https://beta.ruff.rs
name: ruff_and_ty
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ruff_and_ty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
      - run: uvx ruff check --output-format=github
      - run: uv sync --group=test
      - run: uv run --with=ty ty check --output-format=github
